# General
title: Hive Alley Tales
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to discover Hive Alley and its Tales. I started this beekeeping blog with the aim of sharing my experiences and thoughts as a beginner beekeeper. Taking my first steps in beekeeping has led me to many questions and ideas, which I want to share with other aspiring beekeepers and enthusiasts. Together, let's explore the endlessly fascinating world of bees.
github_username: apicrap
# Serving
# domain: karjetanav.eu
url: https://karjetanav.eu/ # http://127.0.0.1:4000/ # "https://apicrap.github.io/"
baseurl: "" # "/apiblog/"

# Outputting
timezone: Europe/Tallinn

# Build settings
theme: null
sass:
  sass_dir: _sass
  style: expanded
  #load_paths:
  #- "."
language_default: et

defaults:
  - scope:
      path: "_pages/en"
    values:
      language: "en"
  - scope:
      path: "_pages/et"
    values:
      language: "et"
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      permalink: "/:title"
      language: en
      excerpt_separator: "<!--more-->"
  - scope:
      path: "_posts/et"
      type: "posts"
    values:
      permalink: "/:title"
      language: et
      excerpt_separator: "<!--rohkem-->"
  - scope:
      path: "assets/images"
    values:
      image: true
feed:
  path: "/feed/et.xml"
  tags:
    path: "/feed/"
    only:
      - et
      - en
  posts_limit: 20
  disable_in_development: true

include: [_pages]
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed

# Conversion
excerpt_separator: ""
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
#exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/

# For GitHub Pages
lsi: false
safe: true
source: ""
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
